//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public string Email { get; set; }
        public string Message { get; set; }
    
        public virtual Companies Companies { get; set; }
    }
}
