//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationProject2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T1518
    {
        public int AttackID { get; set; }
        public string AttackResult { get; set; }
        public string CompanyName { get; set; }
    }
}
